Added support for  *webp images
modx-pro/miniShop2 pull request #318
Opened 2019-06-07 10:35 UTC by biz87

MiniShop2 not working with new progressive MIME Type image/webp. This commit fix it.

2019-06-07 10:36 UTC, biz87 commented
Добавл поддержку загрузки изображений формата webp

2019-08-28 18:39 UTC, Ibochkarev requested changes
Прошу изменить

2019-08-28 18:39 UTC, Ibochkarev commented on core/components/minishop2/processors/mgr/gallery/upload.class.php
> +            }elseif(strpos($data['name'], '.webp') !== false){
```suggestion
            } elseif (strpos($data['name'], '.webp') !== false) {
```

2019-08-28 18:46 UTC, Ibochkarev approved these changes

2019-08-28 18:46 UTC, merged

2022-02-16 00:15 UTC, amakeru commented
![image](https://user-images.githubusercontent.com/2700397/154171761-bf4f6ecc-69d7-4131-ae62-1de9b2c892f4.png)

Если в галерею загружать исходник в webp, то превьюшки не рендерятся

2022-02-16 04:30 UTC, Ibochkarev commented
@amakeru версии minishop2 / modx ?

2022-02-16 05:12 UTC, amakeru commented
@Ibochkarev 2.9.3-pl / 2.8.3-pl на modhost

2022-02-16 06:16 UTC, Ibochkarev commented
> @Ibochkarev 2.9.3-pl / 2.8.3-pl на modhost

проверим

2022-05-15 10:43 UTC, Denimsmurf commented
> > @Ibochkarev 2.9.3-pl / 2.8.3-pl на modhost
> 
> проверим

Подскажите Иван не удалось проверить?