Изменил порядок вкладок в товаре
modx-pro/miniShop2 pull request #376
Opened 2019-10-12 16:05 UTC by Ruslan-Aleev

### Что оно делает?
Переместил вкладки "Группы ресурсов" и "Настройки" в конец соответствующих табов.

![tabs](https://user-images.githubusercontent.com/12523676/65493761-8c481000-dec4-11e9-8ec8-49eef0c942da.png)

### Зачем это нужно?
Полезнее для UX, теперь вкладки, которые часто используются ближе к началу.

### Связанные проблема(ы)/PR(ы)
https://github.com/bezumkin/miniShop2/issues/367

2019-10-13 06:15 UTC, GulomovCreative commented on assets/components/minishop2/js/mgr/product/update.js
> +                var resource_groups_tab = item.items.pop();
Ты уверен, что таким образом выбираешь таб Resource Groups?

2019-10-13 06:44 UTC, GulomovCreative requested changes
Небольшое изменение и погнали ;)

2019-10-13 06:44 UTC, GulomovCreative commented on assets/components/minishop2/js/mgr/product/update.js
>                      item.items.push(this.getGallery(config));
```suggestion
                    item.items.splice(2, 0, this.getGallery(config));
```

Лучше сделай вот так, а свой добавленный код убери

2019-10-13 06:44 UTC, GulomovCreative commented on assets/components/minishop2/js/mgr/product/update.js
> +                // Get the "Resource Groups" tab to move it to the end
```suggestion
```

2019-10-13 06:44 UTC, GulomovCreative commented on assets/components/minishop2/js/mgr/product/update.js
> +                var resource_groups_tab = item.items.pop();
```suggestion
```

2019-10-13 06:44 UTC, GulomovCreative commented on assets/components/minishop2/js/mgr/product/update.js
> +                item.items.push(resource_groups_tab);
```suggestion
```

2019-10-15 05:45 UTC, GulomovCreative approved these changes

2019-10-15 05:51 UTC, Ibochkarev approved these changes

2019-10-15 05:52 UTC, merged