Нумерация заказа MS2
modx-pro/miniShop2 pull request #393
Opened 2020-01-05 22:28 UTC by CrazyBoy49z

### Что оно делает?

#370

### **Внимание код не тестировал нужно, проверить, по логике должно работать. Переводи не делал**

2020-01-05 23:21 UTC, Ruslan-Aleev commented on core/components/minishop2/lexicon/ru/setting.inc.php
> +$_lang['setting_ms2_order_format_num_desc'] = 'Формат нумерации заказа, Доступние значения PHP date: "Y,y,m,d,j".';
Тут опечатка, лучше так написать:
`Доступные значения в формате PHP date(): "Y, y, m, d, j".`

2020-01-05 23:33 UTC, CrazyBoy49z commented on core/components/minishop2/lexicon/ru/setting.inc.php
> +$_lang['setting_ms2_order_format_num_desc'] = 'Формат нумерации заказа, Доступние значения PHP date: "Y,y,m,d,j".';
Спасибо исправил

2020-05-04 21:00 UTC, webinmd commented
Протестировал, системная настройка **ms2_order_format_num_separator** никак не участвует в формировании номера заказа. Там всегда получаем "/"

https://github.com/bezumkin/miniShop2/pull/393/commits/1dcc39b1db0ac5a088e1ebd0e2eb6cecabccf6bc#diff-081fcf6573330c008ba49f7c4731cdf4R600

2020-05-05 03:01 UTC, Ibochkarev requested changes
Прошу поправить по комментариям Евгения. Спасибо

2020-05-06 01:47 UTC, DetaliDigital commented
Изменение года работает, изменил настройку ms2_date_format значение %Y 

![изображение](https://user-images.githubusercontent.com/20732384/81131239-29871e80-8f53-11ea-9d8a-bea0ae894a0b.png)

в итоге номер заказа изменился

![изображение](https://user-images.githubusercontent.com/20732384/81131281-50ddeb80-8f53-11ea-8515-1584c0dc362c.png)

Изменение префикса не работает ms2_order_format_num_separator поставил значение - 

![изображение](https://user-images.githubusercontent.com/20732384/81131610-66074a00-8f54-11ea-87ea-c78e2d7d81a9.png)

получаем 

![изображение](https://user-images.githubusercontent.com/20732384/81131704-abc41280-8f54-11ea-893d-86fe17373d3a.png)

2020-05-06 02:00 UTC, DetaliDigital commented
Я бы сделал следующим образом. В варианте который предложил @CrazyBoy49z  настройка отвечает за определенное действие. Если посмотреть на ISSUE (ссылка на него есть в PR), то можно представить сколько будет в итоге настроек если выполнить ISSUE на 100%
Я предлагаю изменить настройку на одну новую опцию, в которой будет содержаться JSON массив.
К примеру:
{"prefix":"MS2-","date":"Y","separator":''-'}

Я понимаю, что в данном участке много нюансов, которые мы жарко обсуждали. Но я уверен, что в итоге у нас все получится.

2020-05-06 05:11 UTC, CrazyBoy49z commented
Спасибо парни, исправлю по возможности

2020-05-07 09:12 UTC, webinmd commented
> Я предлагаю вести всего одну новую опцию, в которой будет содержаться JSON массив. Мы уже встречали такой вариант ввода и мне кажется он оптимальный для текущей задачи.
> 
> **К примеру:**
> `{"prefix":"MS2-","date":"%Y","separator":'"-"}`

Давайте не усложнять этот функционал, сейчас никто не запрещает добавить префис перед датой, он точно также работает. Я проверял этот момент. 
ТО есть если вписать не просто %Y а MS2-%Y то в номер заказа всё записывается. 

Осталось сделать так чтобы разделитель подставлялся указанный и всё.

2020-05-07 09:43 UTC, CrazyBoy49z commented
> Осталось сделать так чтобы разделитель подставлялся указанный и всё.

Нашёл ошибку у себя в коде, только освобожусь исправлю

2020-05-16 21:50 UTC, alroniks requested changes
Верю, что код писался впопыхах, но все же его нужно привести в порядок.

2020-05-16 21:50 UTC, Alroniks commented on core/components/minishop2/model/minishop2/msorderhandler.class.php
> +        $formatNumSeparator = trim(preg_replace("/[^,\/\-]/", '', "\/"));
Нужно из опции тоже вытаскивать, а то опция как бы есть, но бесполезна.

2020-05-16 21:50 UTC, Alroniks commented on core/components/minishop2/model/minishop2/msorderhandler.class.php
> +            $num = "{$cur}{$formatNumSeparator}0";
Небезопасно. Лучше использовать функцию `sprintf`. По коду ниже - аналогично.

2020-05-16 21:50 UTC, Alroniks commented on core/components/minishop2/model/minishop2/msorderhandler.class.php
> +        $num = "{$cur}{$formatNumSeparator}" . ($num[1] + 1);
Дикое переопределение переменных. Можно переписать чуть более наглядно.

2020-05-16 21:50 UTC, Alroniks commented on core/components/minishop2/model/minishop2/msorderhandler.class.php
> +        }
```suggestion
        $cut = $formatNum ? strftime($formatNum) : date('ym');
```

2020-05-16 21:50 UTC, Alroniks commented on core/components/minishop2/model/minishop2/msorderhandler.class.php
> +        }
Да и вообще, здесь это условие вообще не нужно, так как getOption в default всегда вернет значение `ym`.

2020-06-06 10:07 UTC, CrazyBoy49z commented on core/components/minishop2/model/minishop2/msorderhandler.class.php
> +        $num = "{$cur}{$formatNumSeparator}" . ($num[1] + 1);
Поправлю только, доберусь, ошибки есть так набросал в браузере, я б совсем завел новое поле в таблице на количество, но думаю это уже нужно будет добавить в minishop3

2020-06-09 19:27 UTC, webinmd approved these changes

2020-06-09 20:06 UTC, webinmd approved these changes

2020-06-10 03:04 UTC, Ibochkarev commented
@DetaliDigital прошу еще раз протестировать.

2020-06-10 03:06 UTC, Ibochkarev commented on core/components/minishop2/model/minishop2/msorderhandler.class.php
> +        );
```suggestion
        $separator = trim(
            preg_replace("/[^,\/\-]/", '',
                $this->modx->getOption('ms2_order_format_num_separator', null, '/')
            )
        );
```

2020-06-30 17:51 UTC, merged

2026-08-18 11:12 UTC, adm93rus commented
Всем привет, на данный момент если очистить настройку ms2_order_format_num, то формат номера заказа принимает дефолтный вид, вместо того, что бы оставить только номер без префикса.
Это можно пофиксить?