Added sorting sortOptions in msOptions, msProductOptions
modx-pro/miniShop2 pull request #407
Opened 2020-04-08 12:14 UTC by Ibochkarev

### Что оно делает?

Добавляет сортировку в сниппеты msOptions, msProductOptions

### Зачем это нужно?

Новый функционал

### Связанные проблема(ы)/PR(ы)
https://github.com/vgrish/miniShop2/commit/22a8e10efac0b87114395c8932fe822800e5d2dd

2020-05-08 11:57 UTC, webinmd requested changes
Если получится, в лексиконах в строке
_Указывает порядок сортировки значений опций. Передаются строкой, например, "size:SORT_DESC:SORT__

После например, - вместо запятой поставить двоеточие, в английской версии тоже

2020-05-11 18:24 UTC, Ibochkarev commented
> Если получится, в лексиконах в строке
> _Указывает порядок сортировки значений опций. Передаются строкой, например, "size:SORT_DESC:SORT__
> 
> После например, - вместо запятой поставить двоеточие, в английской версии тоже

А в остальном работает?

2020-05-11 18:25 UTC, webinmd commented
да, всё отлично работает

2020-05-11 18:26 UTC, webinmd approved these changes

2020-05-16 21:57 UTC, alroniks requested changes
Не думаю, что мое мнение будет что-то сильно значить, но я бы улучшил реализацию.

2020-05-16 21:57 UTC, Alroniks commented on core/components/minishop2/elements/snippets/snippet.ms_options.php
> +        $sort = explode(':', $sort);
`list($key, $order, $type) = explode(':', $sort);`
и условия ниже можно сильно сократить, сделав код чище

2020-05-16 21:57 UTC, Alroniks commented on core/components/minishop2/elements/snippets/snippet.ms_product_options.php
> +if (!empty($scriptProperties['sortOptions'])) {
Этот код дублируется 2 раза в разных снипетах, в будущем кто-то поправит в одном, а в другом забудет или не будет знать, и получим новые ошибки. Следует вынести этот код (он в целом не зависит от данных) в функцию класса и вызывать ее в снипете.

2020-05-19 07:08 UTC, Ibochkarev commented on core/components/minishop2/elements/snippets/snippet.ms_product_options.php
> +if (!empty($scriptProperties['sortOptions'])) {
@Alroniks будет возможность переписать указанное выше после вливания? Так как я удалил репозиторий вместе с ветками и не могу вночить изменения.

2020-06-07 03:18 UTC, merged