#398 clone msCategory options on subcategory creation
modx-pro/miniShop2 pull request #412
Opened 2020-04-27 06:29 UTC by VoiD2008

### Что оно делает?
Клонирует опции для товаров категории при создании подкатегории

### Зачем это нужно?
Issue 398 отмечена как баг

2020-04-29 06:39 UTC, GulomovCreative requested changes
Спасибо большое за PR, всё работает, единственное попрошу немного оформление кода поправить

2020-04-29 22:44 UTC, VoiD2008 commented
Не совсем понял, что именно в оформлении надо было поправить )) 
Слегка пересобрал

2020-05-05 13:06 UTC, GulomovCreative approved these changes

2020-05-07 19:54 UTC, Ibochkarev approved these changes

2020-05-07 19:55 UTC, merged