Update getnodes.class.php
modx-pro/miniShop2 pull request #413
Opened 2020-04-27 09:56 UTC by Boshnik

Выводить только категории товара, вместо всех ресурсов.

2020-04-27 12:45 UTC, Ruslan-Aleev commented
Если категория minishop2 вложена в обычный ресурс, то в списке категорий она не будет отображаться:

![cat](https://user-images.githubusercontent.com/12523676/80373616-fdf29d00-889d-11ea-9b0c-7e49139b26fe.png)

2020-04-27 17:28 UTC, webinmd commented
Протестировал, если вложенность в простые ресурсы, то не выводится в дереве ничего.

2020-04-27 17:33 UTC, Ruslan-Aleev commented
@webinmd А зачем закрыли-то? Может @Boshnik другое решение предложит.

2020-04-27 17:38 UTC, webinmd commented
> @webinmd А зачем закрыли-то? Может @Boshnik другое решение предложит.

Откроем обратно, мне казалось что если PR не проходит тестирование, то нет смысла ему висеть в открытых, если не так, открой обратно. Ни в коем случае не хотел кого-то обидеть :)

2020-04-28 16:19 UTC, VoiD2008 commented
Так все ж правильно, запрос на включение в мастер должен отклоняться если не проходит тестирование.
Я конечно могу ошибаться, но на первый взгляд решение в комите неверное. В нем изначально запрос ограничивают классом msCategory, а цель исправления отобразить дерево в том числе и с ветвями обычных категорий, а откуда им взяться если ищем только по msCategory.
Навскидку это и не должно работать

2020-04-28 16:22 UTC, webinmd commented
Цель исправления отобразить дерево из **категорий** магазина, у которых класс msCategory, а не все ресурсы сайта, но проблема в том, что если эта категория имеет родителя с другим классом, то она не отобразится в дереве.

2020-04-28 16:32 UTC, VoiD2008 commented
Ну правильно, но дерево или одна из его ветвей не может расти из пустоты, а родителем ветви в примере получается обычная modResource с is_folder == 1
Ее тоже нужно отображать, иначе дерево просто не сможет построиться, либо писать обходчик который будет поднимать ветвь до ближайшего валидного родителя, что имхо просто некорректно.

2020-04-28 16:49 UTC, VoiD2008 commented
![test](https://user-images.githubusercontent.com/8608597/80514376-17244800-8989-11ea-9022-b6c021691605.png)
проверил у себя на модели, ошибки в принципе не существует.
Как видно на скриншоте дерево включает в себя так-же вложенные в обычные категории элементы.
Даже проверил разные комбинации с флагами опубликован\скрыт в меню
все работает. И вообще надо сначала Issue заводить, а потом уже PR когда речь о багах...
Вероятно ошибка у ТС в чемто другом

2020-04-28 16:52 UTC, webinmd commented
Попробуй сделать в О салоне дочерний ресурс, у меня в дерево попадают is_folder == 1.
Автор хотел избавить компонент от этой проблемы

2020-04-28 17:06 UTC, VoiD2008 commented
> Попробуй сделать в О салоне дочерний ресурс, у меня в дерево попадают is_folder == 1.
> Автор хотел избавить компонент от этой проблемы

те. разорвать дерево, выдрав из него не минишоповые ноды?
процессор строит ветви дерева динамически, а не все дерево сразу
он не может знать есть ли в обычной ноде isfolder ноды msCategory
поэтому в дереве видны все ресурсы являющиеся контейнерами, при этом как показывают тесты, ноды с классом не msCategory  отображаются без чекбокса
нужн либо писать тяжелый процессор, который будет строить дерево целиком со всеми проверками на тип ресурса и переписывать js который это дерево рендерит, либо не заниматься фигней :)

ИМХО ошибки в принципе тут нет никакой

2020-04-29 06:43 UTC, GulomovCreative requested changes
@Boshnik Спасибо большое за PR, но он приводит к ошибкам которые выше были описаны, если можешь то исправь пожалуйста

2020-04-29 08:14 UTC, Boshnik commented
Я не знаю зачем в обычный ресурс помещать категорию. Ну, допустим, что так и нужно.
Можно, уменьшить дерево категорий удалив хотя бы ресурсы, которые не имеют родителей.
```
if ($itemArray['classKey'] != 'msCategory') {
    unset($itemArray['checked']);
    if(!$itemArray['hasChildren']) {
        unset($itemArray);
    } 
}
```
Но, это не то, что я хотел бы увидеть, 
Другого быстрого решения пока не нашел.

2020-05-01 10:58 UTC, Ruslan-Aleev commented
@Boshnik Переименуйте настройки в `setting_ms2_categories_show_only` и `setting_ms2_categories_show_only_desc`, так, как-то логичнее будет. Хоть настройка в товаре, но настройка затрагивает категории только.

2020-05-01 11:22 UTC, Ruslan-Aleev commented
@Boshnik А универсальнее нет решения? К примеру, показывать только категории + ресурс с дочерними, при условии, что дочерние являются категорией?
Кстати, PR связан с https://github.com/bezumkin/miniShop2/issues/360

2020-05-01 12:03 UTC, Ruslan-Aleev commented
Вообще, по-факту, тут есть 2 недочета:
1. Если категория в обычном ресурсе, то она не отображается (т.к. `array('class_key' => 'msCategory')`)
2. При перетаскивании категории, к примеру, даже в другую категорию (или ресурс), то родительская категория не будет отображаться (т.к. isfolder не встанет в true, https://github.com/bezumkin/miniShop2/blob/master/core/components/minishop2/processors/mgr/category/getnodes.class.php#L60), а это уже баг MODX - https://github.com/modxcms/revolution/issues/14747

PR логически связан с https://github.com/bezumkin/miniShop2/issues/360

2020-05-01 20:15 UTC, Boshnik commented
Переименовал системную настройку.

> 1. В текущем решении, если категория в обычном ресурсе, то она не отображается

Если отключить системную настройку, то отображается, а по умолчанию показываем только категории.

2020-05-02 07:39 UTC, Ibochkarev requested changes

2020-05-02 07:39 UTC, Ibochkarev commented on core/components/minishop2/lexicon/ru/setting.inc.php
> +$_lang['setting_ms2_categories_show_only_desc'] = 'Отключите эту опцию, если категории вложенные в обычные ресурсы.';
```suggestion
$_lang['setting_ms2_categories_show_only_desc'] = 'Отключите эту опцию, если категории вложенны в обычные ресурсы.';
```

2020-05-13 05:07 UTC, DetaliDigital commented
> Я не знаю зачем в обычный ресурс помещать категорию. Ну, допустим, что так и нужно.
> Можно, уменьшить дерево категорий удалив хотя бы ресурсы, которые не имеют детей.
> 
> ```
> if ($itemArray['classKey'] != 'msCategory') {
>     unset($itemArray['checked']);
>     if(!$itemArray['hasChildren']) {
>         unset($itemArray);
>     } 
> }
> ```
> 
> Но, это не то, что я хотел бы увидеть,
> Другого быстрого решения пока не нашел.

Да такое часто бывает. Особенно если тип сайта корпоративный и мы используем MS2 как вспомогательный элемент. Так же иногда нужен ресурс разделитель для того что бы использовать PdoTools. А иногда так сделали просто не задумались зачем это сделали так, в данном случае это обратная совместимость.

Но идея правильная @Boshnik . Молодец)

2020-09-04 14:24 UTC, Ruslan-Aleev commented on core/components/minishop2/lexicon/ru/setting.inc.php
> +$_lang['setting_ms2_categories_show_only'] = 'Показывать только категории';
Тут имеет смысл чуть конкретнее написать:
`Показывать только категории в дереве категорий товара`

2020-09-04 14:26 UTC, Ruslan-Aleev commented
Так-то все работает, но нужно подождать выхода MODX 2.8, т.к. исправление @GulomovCreative по поводу `isfolder` влито, иначе могут быть непонятки.

2020-09-04 14:39 UTC, Ruslan-Aleev commented
Хотя нет, я поторопился, т.к. если категория расположена в ресурсе (не категории), то придется выключать настройку, но тогда смысл PR теряется.
В общем, как мне кажется, стоит влить только это исправление - https://github.com/bezumkin/miniShop2/pull/413#issuecomment-621056333 + исправление isfolder в ядре MODX (которое влито в 2.8), думаю, это оптимальный вариант будет.

2020-11-14 08:40 UTC, Ibochkarev commented
@webinmd @GulomovCreative что скажете?

2020-11-14 08:41 UTC, Ibochkarev requested changes

2020-11-14 08:41 UTC, Ibochkarev commented on core/components/minishop2/lexicon/ru/setting.inc.php
> +$_lang['setting_ms2_categories_show_only'] = 'Показывать только категории';
```suggestion
$_lang['setting_ms2_categories_show_only'] = 'Показывать только категории в дереве категорий товара';
```

2020-12-14 18:41 UTC, closed without merging