Добавление настройки переключения режима работы корзины с контекстами…
modx-pro/miniShop2 pull request #424
Opened 2020-05-16 08:29 UTC by Alexij2

**Что делает?**
Создает новую настройку **ms2_cart_context_init.**
**Зачем?**
Чтобы переключать вид инициализации корзины в контекстах. А именно если настройка = ДА, то корзина одна на все контексты, если НЕТ, то корзины разные.
**Дополнительно**
Так же добавлены переводы этой настройки на все языки, в которых есть файл /lang/settings.inc.php.

2020-05-16 09:08 UTC, Ibochkarev requested changes

2020-05-16 09:08 UTC, Ibochkarev commented on core/components/minishop2/lexicon/ru/setting.inc.php
> +$_lang['setting_ms2_cart_context_init_desc'] = 'Если Да, корзина одна на все контексты. Если Нет - у каждого контекста своя корзина.';
```suggestion
$_lang['setting_ms2_cart_context_init'] = 'Использовать единую корзину для всех контекстов?';
$_lang['setting_ms2_cart_context_init_desc'] = 'Если включено, то используется общая корзина для всех контекстов. Если выключено - то у каждого контекста используется своя корзина.';
```

2020-05-17 07:54 UTC, Alexij2 commented
Пул реквест бесполезен. Закрываю сам за не надобностью.

2020-05-17 08:34 UTC, Alexij2 commented
Прошу прощения.
Все работает. Разобрался со схемой работы.

2020-06-07 20:32 UTC, CrazyBoy49z commented on core/components/minishop2/model/minishop2/mscarthandler.class.php
> +                }
$ctx_key = 'web';
               if (!$this->modx->getOption('ms2_cart_context', null, '', true) ){
                    $ctx_key = $this->modx->context->get('key');
                }

2020-06-07 20:33 UTC, CrazyBoy49z commented on core/components/minishop2/model/minishop2/mscarthandler.class.php
> +        if ($this->modx->getOption('ms2_cart_context', null, '', true) == 1){
if ($this->modx->getOption('ms2_cart_context', null, '', true)){
            $ctx = 'web';
        }

2020-06-07 20:53 UTC, CrazyBoy49z requested changes

2020-06-07 20:53 UTC, CrazyBoy49z commented on core/components/minishop2/model/minishop2/mscarthandler.class.php
> +        if ($this->modx->getOption('ms2_cart_context', null, '', true) == 1){
```suggestion
        if ($this->modx->getOption('ms2_cart_context', null, '', true)){
```

2020-06-07 20:53 UTC, CrazyBoy49z commented on core/components/minishop2/model/minishop2/mscarthandler.class.php
> +                }
```suggestion
                $ctx_key = 'web';
                if (!$this->modx->getOption('ms2_cart_context', null, '', true)){
                    $ctx_key = $this->modx->context->get('key');
                }
```

2020-06-09 20:51 UTC, webinmd approved these changes
Протестировал в нескольких контекстах, товары в корзине есть, вроде как работает

2020-06-10 22:19 UTC, GulomovCreative commented
> Протестировал в нескольких контекстах, товары в корзине есть, вроде как работает

Я этого и остерегаюсь, чтобы не было "вроде бы"

2020-06-10 22:20 UTC, GulomovCreative commented
@Ibochkarev Настаиваю оставить PR для след. обновления, не 2.5.1

2020-06-11 07:37 UTC, webinmd commented
> > Протестировал в нескольких контекстах, товары в корзине есть, вроде как работает
> 
> Я этого и остерегаюсь, чтобы не было "вроде бы"

а тут только на реальном сайте протестировать получится, вот так вот в тепличных условиях легко упустить какие-то мелочи

2020-06-11 21:35 UTC, webinmd commented
По идее если внести эти изменения, то по сути функция отключена изначально и все будет работать как и раньше, можно влить в следующую версию с пометкой что функционал тестируется. Тогда кому надо даст реальный отзыв с рабочего проекта и ничего никому не сломается

2020-06-13 01:59 UTC, GulomovCreative commented
> По идее если внести эти изменения, то по сути функция отключена изначально и все будет работать как и раньше, можно влить в следующую версию с пометкой что функционал тестируется. Тогда кому надо даст реальный отзыв с рабочего проекта и ничего никому не сломается

Отличная идея, согласен.

2020-06-13 22:08 UTC, Alexij2 commented
Сейчас данная штука работает на боевом сайте уже пару месяцев (если не больше).
Работает именно с URL формата site.gosh/{context}/{url_site_region}.
версия modx 2.6.5 с minishop2 2.2.
Так же я тестировал работу и так - и так на новом minishop2 2.5. Добавление в корзину, отработка ее. 
Просто в единой корзине заказы от главного контекста идут.
в общем-то идея с введением с пометкой эксперимент - как компромис. Тем более по умолчанию будет выключено. Что не повлияет на работу по стандарту.

2020-07-09 18:14 UTC, webinmd commented
Коллеги, отпишитесь кто протестировал, можно ли вливать, или нужны какие-то доработки?
Я протестировал на рабочем сайте, работает как описано. По умолчанию отключено, поэтому никаких неудобств при обновлении не доставляет

2020-07-12 14:55 UTC, CrazyBoy49z requested changes

2020-07-12 14:55 UTC, CrazyBoy49z commented on core/components/minishop2/lexicon/uk/setting.inc.php
> +$_lang['setting_ms2_cart_context'] = 'Використовувати єдину кошик для всіх контекстів?';
```suggestion
$_lang['setting_ms2_cart_context'] = 'Використовувати єдину кошик для всіх контекстів?';

```
$_lang['setting_ms2_cart_context'] = 'Використовувати єдиний кошик для всіх контекстів?';

2020-07-12 14:55 UTC, CrazyBoy49z commented on core/components/minishop2/lexicon/uk/setting.inc.php
> +$_lang['setting_ms2_cart_context_desc'] = 'Якщо включено, то використовується загальний кошик для всіх контекстів. Якщо вимкнено - то у кожного контексту використовується своя кошик.';
```suggestion
$_lang['setting_ms2_cart_context_desc'] = 'Якщо включено, то використовується загальний кошик для всіх контекстів. Якщо вимкнено - то у кожного контексту використовується своя кошик.';

```
$_lang['setting_ms2_cart_context_desc'] = 'Якщо включено, то використовується загальний кошик для всіх контекстів. Якщо вимкнено - то у кожного контексту використовується свій кошик.';

2020-07-13 22:57 UTC, CrazyBoy49z approved these changes

2020-07-17 05:29 UTC, merged