Добавил ссылку на системные настройки в меню miniShop2
modx-pro/miniShop2 pull request #430
Opened 2020-06-02 14:45 UTC by Ruslan-Aleev

### Что оно делает?
Добавил ссылку на системные настройки в меню пакета miniShop2:

![ms2-ss](https://user-images.githubusercontent.com/12523676/83533851-c27c6b80-a4f8-11ea-8844-d8e521ed4df9.gif)

### Зачем это нужно?
Во-первых, полезно для UX - меньше кликов.
Во-вторых, для новичков будет понятнее как и что настраивается, и где искать настройки (все в одном месте).

### Связанные проблема(ы)/PR(ы)
https://github.com/bezumkin/miniShop2/issues/429

2020-06-04 13:14 UTC, GulomovCreative requested changes
Отличная идея, только необходимо добавить namespace и уточнить права

2020-06-04 13:14 UTC, GulomovCreative commented on _build/data/transport.menu.php
> +        'namespace' => '',
```suggestion
        'namespace' => 'core',
        'permissions' => 'settings',
```

2020-06-04 13:20 UTC, GulomovCreative requested changes
Вот так

2020-06-04 13:20 UTC, GulomovCreative commented on _build/data/transport.menu.php
> +        'namespace' => '',
```suggestion
        'namespace' => 'core',
        'permissions' => 'settings',
```

2020-06-04 13:37 UTC, GulomovCreative approved these changes

2020-06-07 20:20 UTC, CrazyBoy49z approved these changes

2020-06-07 20:20 UTC, CrazyBoy49z commented on core/components/minishop2/lexicon/en/default.inc.php
> +$_lang['ms2_system_settings_desc'] = 'miniShop2 system settings ';
Удалить пробел в конце

2020-06-07 20:21 UTC, Ibochkarev requested changes

2020-06-07 20:21 UTC, Ibochkarev commented on core/components/minishop2/lexicon/en/default.inc.php
> +$_lang['ms2_system_settings_desc'] = 'miniShop2 system settings ';
```suggestion
$_lang['ms2_system_settings_desc'] = 'miniShop2 system settings';
```

2020-06-08 09:28 UTC, Ruslan-Aleev commented
Ребята, может ссылку и на лексиконы добавить? Типа "Системные настройки" и ниже "Лексиконы". Для логики и единообразия. Так-то лексиконы тоже меняются иногда... Или это лишнее?
@GulomovCreative Баха против, а я в сомнениях :)

2020-06-09 20:21 UTC, webinmd approved these changes

2020-06-10 03:01 UTC, merged