Refactoring `sortOptionValues` property
modx-pro/miniShop2 pull request #433
Opened 2020-06-07 05:01 UTC by gvozdb

### Что оно делает?

Рефакторинг https://github.com/bezumkin/miniShop2/pull/407

2020-06-07 05:05 UTC, Ibochkarev requested changes

2020-06-07 05:05 UTC, Ibochkarev commented on core/components/minishop2/lexicon/en/properties.inc.php
> +$_lang['ms2_prop_sortOptionValues'] = 'Specifies the sort order of option values. Passed as a string, e.g., "size:SORT_DESC:SORT_NUMERIC:100,color:SORT_ASC:SORT_STRING"';
```suggestion
$_lang['ms2_prop_sortOptionValues'] = 'Specifies the sort order of option values. Passed as a string, e.g.: "size:SORT_DESC:SORT_NUMERIC:100,color:SORT_ASC:SORT_STRING"';
```

2020-06-07 05:05 UTC, Ibochkarev commented on core/components/minishop2/lexicon/ru/properties.inc.php
> +$_lang['ms2_prop_sortOptionValues'] = 'Указывает порядок сортировки значений опций. Передаются строкой, например, "size:SORT_DESC:SORT_NUMERIC:100,color:SORT_ASC:SORT_STRING"';
```suggestion
$_lang['ms2_prop_sortOptionValues'] = 'Указывает порядок сортировки значений опций. Передаются строкой, например: "size:SORT_DESC:SORT_NUMERIC:100,color:SORT_ASC:SORT_STRING"';
```

2020-06-09 21:04 UTC, webinmd approved these changes

2020-06-10 03:02 UTC, Ibochkarev approved these changes

2020-06-10 03:02 UTC, merged