Возможность обновления нескольких мини-корзин на странице.
modx-pro/miniShop2 pull request #436
Opened 2020-06-10 21:39 UTC by Alexij2

### Что оно делает?
Возможность обновления нескольких мини-корзин на странице.
Изменения коснулись скриптов и 1 чанка миникорзины, а именно:
замена идентификатора msMiniCart на CSS класс msMiniCart.
При этом поддержка идентификатора продолжентся для совместимости.

### Зачем это нужно?
Нужно для использования нескольких мини корзин.

2020-06-10 22:17 UTC, GulomovCreative requested changes

2020-06-10 22:17 UTC, GulomovCreative commented on assets/components/minishop2/js/web/default.js
> +                if ($('miniShop2.Cart.miniCart').length > 0) {
У тебя тут ошибка в коде

2020-06-11 10:20 UTC, CrazyBoy49z requested changes
Делайте с оптимизацией по коду, не делайте +100500 выборок в запросах

2020-06-11 10:20 UTC, CrazyBoy49z commented on assets/components/minishop2/js/web/default.js
> +                    var $miniCart = $(miniShop2.Cart.miniCart);
```suggestion
                var $miniCart = $(miniShop2.Cart.miniCart);
                if ($miniCart.length > 0) {
                   
```

2020-06-11 10:22 UTC, CrazyBoy49z commented on core/components/minishop2/elements/chunks/chunk.ms_minicart.tpl
> +<div class="msMiniCart{$total_count > 0 ? ' full' : ''}">
```suggestion
<div id="msMiniCart"  class="msMiniCart{$total_count > 0 ? ' full' : ''}">
```

2020-06-11 10:23 UTC, CrazyBoy49z commented on core/components/minishop2/elements/chunks/chunk.ms_minicart.tpl
> +<div class="msMiniCart{$total_count > 0 ? ' full' : ''}">
Это лучше оставить так как сломаете обновлением +100500 сайтов

2020-06-11 10:38 UTC, CrazyBoy49z requested changes

2020-06-11 10:38 UTC, CrazyBoy49z commented on assets/components/minishop2/css/web/default.css
> +.msMiniCart.full .not_empty { display: block; }
```suggestion
#msMiniCart, .msMiniCart { font-size: .8em; }
#msMiniCart h5, .msMiniCart h5 { margin: 0; }
#msMiniCart .empty, .msMiniCart .empty { display: block; }
#msMiniCart .not_empty, .msMiniCart .not_empty { display: none; }
#msMiniCart.full .empty, .msMiniCart.full .empty { display: none; }
#msMiniCart.full .not_empty, .msMiniCart.full .not_empty { display: block; }
```

2020-06-11 10:38 UTC, CrazyBoy49z commented on assets/components/minishop2/css/web/default.css
>  #msMiniCart.full .not_empty { display: block; }
Удалить 19-24 строки

2020-06-15 19:33 UTC, CrazyBoy49z commented
Удалить ещё строки дублирующие в CSS 19-24

2020-06-15 20:05 UTC, Alexij2 commented on assets/components/minishop2/js/web/default.js
> +                if ($('miniShop2.Cart.miniCart').length > 0) {
да, сори.. точно. кавычки по привычке. Спасибо.

2020-06-16 08:15 UTC, CrazyBoy49z approved these changes

2020-06-16 12:38 UTC, CrazyBoy49z commented on assets/components/minishop2/js/web/default.js
> +                if ($('miniShop2.Cart.miniCart').length > 0) {
Уже исправлено

2020-06-16 12:39 UTC, CrazyBoy49z commented
Парни проверяйте до конца, по коду всё норм

2020-06-17 10:01 UTC, GulomovCreative commented
Даже после Юры в коде остались недочеты. Вот как код должен выглядеть:

```
var $miniCarts = $(miniShop2.Cart.miniCart).add(miniShop2.Cart.miniCartClass);
if (status['total_count'] > 0 && $miniCarts.length > 0) {
    $miniCarts.each((index,cart) => {
        if (!$(cart).hasClass(miniShop2.Cart.miniCartNotEmptyClass)) {
            $(cart).addClass(miniShop2.Cart.miniCartNotEmptyClass);
        }
    });
}
```

2020-06-19 20:44 UTC, Alexij2 commented
> Даже после Юры в коде остались недочеты. Вот как код должен выглядеть:
> 
> ```
> var $miniCarts = $(miniShop2.Cart.miniCart).add(miniShop2.Cart.miniCartClass);
> if (status['total_count'] > 0 && $miniCarts.length > 0) {
>     $miniCarts.each((index,cart) => {
>         if (!$(cart).hasClass(miniShop2.Cart.miniCartNotEmptyClass)) {
>             $(cart).addClass(miniShop2.Cart.miniCartNotEmptyClass);
>         }
>     });
> }
> ```
Ох...
Ребят, вот после такого всякое желание отпадает делать в бесплатном компоненте нововведения от новичка.
1. Если переименование переменных - это ошибка, извините. Лучше я вообще не буду пушить.
2. Вы изменили логику, которая не корректна... Как вы собираетесь идентификатору (каждому!?) присваивать класс? Тут идея в том что мы оставляем поддержку старого и переходим на новое, а именно отказываемся от идентификатора и используем только класс.
3. Я и так знаю что я не профи и не обязательно постоянно повторять, что не правильно или есть недочеты... Помогите лучше кодом сразу исправленным, если видите, что можно лучше, как Юра, например и сделал. Спасибо ему и надеюсь на понимание.

2020-06-27 13:03 UTC, CrazyBoy49z approved these changes

2020-06-28 12:56 UTC, webinmd approved these changes

2020-06-30 17:44 UTC, Ibochkarev commented
@Alexij2 ждем обратную связь по работе улучшения на сайте Pavel Fedortsov (сегодня в чате) и можно вливать.

2020-06-30 20:13 UTC, Alexij2 commented
Все заработало, просто забыл он поставить класс цены и количества дл миникорзины.

2020-06-30 20:21 UTC, merged