add order product's options interface
modx-pro/miniShop2 pull request #491
Opened 2020-11-25 14:38 UTC by biz87

Добавил интерфейс управления опциями товара в заказе для админки

2020-11-27 08:51 UTC, biz87 commented
**Какую решал проблему**
В окне заказа каждый продукт содержит текстовое окно с JSON набором опций
[https://prnt.sc/vr2edz](https://prnt.sc/vr2edz)

Задача сделать удобный интерфейс редактирования подобных опций товара.

Реализован [вот такой интерфейс](https://prnt.sc/vr2gu4)

Также реализована системная настройка  **ms_order_product_options**
Она регулирует какие именно поля выводить для редактирования в новом интерфейсе. 

**Шаги для проверки.** 

- Создать заказ с опциями у товара.   
- Убедиться что ключи опций добавлены в системную настройку.  
- Проверить успешный вывод полей для редактирования. 
- Проверить сохранение обновленных данных
- Убрать часть полей из системной настройки, Убедиться что они исчезли и из интерфейса

2020-11-27 11:21 UTC, webinmd requested changes
Добавить лексиконы для системных настроек

2020-12-03 19:00 UTC, webinmd approved these changes

2020-12-07 06:52 UTC, Ibochkarev requested changes
После вливания обнаружил ошибку:
![Снимок экрана 2020-12-07 в 12 35 59](https://user-images.githubusercontent.com/2138260/101318405-7dac0580-388a-11eb-93ed-6ffb05b408d5.png)

![Снимок экрана 2020-12-07 в 12 43 10](https://user-images.githubusercontent.com/2138260/101318423-83a1e680-388a-11eb-82f4-4cb38bee0ff6.png)

В чанке: tpl.msGetOrder не корректно выводится сумма.

Итого с доставкой должно быть 1050 + 0 = 1050, так как бесплатная доставка от 700 р

Нужно прислать изменения. Также учесть отображение в админке

![Снимок экрана 2020-12-07 в 12 51 05](https://user-images.githubusercontent.com/2138260/101318713-f9a64d80-388a-11eb-95b6-bba5a4dc7dd1.png)

2020-12-09 06:04 UTC, merged