Update snippet.ms_products.php
modx-pro/miniShop2 pull request #500
Opened 2020-12-09 17:52 UTC by Mngatoff

Add support of different return formats

### Обработка параметра return

Добавлена нормальная обработка параметра return с поддержкой форматов sql, json и serialize.
Убрано принудительное создание outputSeparator

### Зачем это нужно?

См. https://github.com/bezumkin/miniShop2/issues/499

### Связанные проблема(ы)/PR(ы)

https://github.com/bezumkin/miniShop2/issues/499

2020-12-10 07:55 UTC, gvozdb commented
Получилось слишком запутано. Нужно сделать код понятнее.

– Переменную `$returnIds` вообще надо выпилить, зачем она, если есть параметр return.
– [Здесь](https://github.com/bezumkin/miniShop2/blob/a9638029803defc63822cf2b55616d31448044ad/core/components/minishop2/elements/snippets/snippet.ms_products.php#L21-L27) записывать данные не в переменную `$return`, а в элемент `$scriptProperties['return']`.
– [Тут](https://github.com/bezumkin/miniShop2/blob/a9638029803defc63822cf2b55616d31448044ad/core/components/minishop2/elements/snippets/snippet.ms_products.php#L173-L175) тоже надо убрать это, оно ни к чему.
– И[ этот кусок](https://github.com/bezumkin/miniShop2/blob/a9638029803defc63822cf2b55616d31448044ad/core/components/minishop2/elements/snippets/snippet.ms_products.php#L240-L247) переписать с учётом всех вышеописанных правок.

2020-12-10 12:49 UTC, Mngatoff commented
> – [Здесь](https://github.com/bezumkin/miniShop2/blob/a9638029803defc63822cf2b55616d31448044ad/core/components/minishop2/elements/snippets/snippet.ms_products.php#L21-L27) записывать данные не в переменную `$return`, а в элемент `$scriptProperties['return']`.
> – [Тут](https://github.com/bezumkin/miniShop2/blob/a9638029803defc63822cf2b55616d31448044ad/core/components/minishop2/elements/snippets/snippet.ms_products.php#L173-L175) тоже надо убрать это, оно ни к чему.

Вырвано из контекста. Смысл как раз в том, чтобы разделить $scriptProperties['return'] и сам $return. 

Первый отвечает за получение данных от pdoFetch (мерджится с $default), в нем могут быть только ids или data. Второй отвечает за вывод пользователю после всех специфичных для msProducts обработок.

Что касается переменной $returnIds, то она там была всегда, и кроме того она является легальным параметром pdoResources, поэтому я ее не стал выпиливать.

2020-12-12 14:53 UTC, EMDM45 commented
Смотрю файл. А вы не путаетесь при разработке/отладке, когда по всему коду раскидан `return` ?
Может лучше и удобнее записывать в конце `return $output;` один раз, а в самом коде присваивать переменной `$output` нужные данные?

2020-12-17 06:59 UTC, biz87 commented
Код действительно очень запутанным получился.  Павел все по делу написал, мне нечего добавить.

2020-12-17 07:02 UTC, biz87 requested changes
Как минимум нужно добавить параметр return к сниппету

2020-12-17 14:43 UTC, Mngatoff commented
ну вы молодцы. типа до этого был сниппет прекрасный и незапутанный, пришел я и всё запутал :) ладно

2020-12-17 14:49 UTC, biz87 commented
Добавил ты 33 новые строки а не 3. 
Алексей ну да было не очень. Стало еще хуже. 
Задачку ты решил - но вот общая картина получается так себе. Мне потом переписывать придется общую читаемость и логику. 
Давай попробуем улучшить сниппет или сократить твой код

2020-12-17 18:36 UTC, EMDM45 commented
> переписывать придется общую читаемость и логику.

Получается схема сниппета такая:

```
$options = [] //массив параметров по-умолчанию
array_merge($options, $scriptPropeties)

//для совместимости
if $options[returnIds] === true 
$options[return] = ids;

//дальше идет код подготовки запроса к БД

if $options[return] = sql {

$output = $sql

} else {

//выборка данных из базы

//тут как раз и происходит обработка данных для нужного вывода: array, json, ids, chunk и т.п.
switch $options[return]

}

return $output
```

Потом уже можно будет оптимизировать разные детали.

2020-12-26 09:20 UTC, Ibochkarev commented
@Mngatoff будет возможность сегодня завтра внести исправления? 
Чтобы в релиз попалою.

2020-12-26 15:07 UTC, Mngatoff commented
@Ibochkarev да, завтра сделаю

2021-02-14 12:40 UTC, DetaliDigital commented
Я хочу обратить внимание на данный документ https://docs.modx.pro/komponentyi/pdotools/obshhie-parametryi#%D0%A1%D0%BF%D0%BE%D1%81%D0%BE%D0%B1%D1%8B-%D0%B2%D1%8B%D0%B7%D0%BE%D0%B2%D0%B0-%D1%87%D0%B0%D0%BD%D0%BA%D0%BE%D0%B2

2021-02-15 06:15 UTC, CrazyBoy49z commented
Не принимать pr завтра постараюсь сделать. Код нуждается в рефакторинге.

2021-02-17 12:26 UTC, CrazyBoy49z requested changes
Ждать новой PR

2021-03-10 05:06 UTC, Ibochkarev commented
@Mngatoff спасибо! 

Закрыто в пользу #553

2021-03-10 05:06 UTC, closed without merging