Добавлены часто требуемые поля в таблицу адреса
modx-pro/miniShop2 pull request #581
Opened 2021-04-11 11:23 UTC by biz87

### Что оно делает?

- Расширена карта объекта адреса
- Добавлены  необходимые резолверы
- Новые поля добавлены в админку
- Новые поля добавлены в чанк заказа
- Новые поля добавлены в лексиконы (ru/en)
### Зачем это нужно?

При заказе товаров с доставкой в больших городах часто очень актуальным становится номер подъезда и этаж, где расположена квартира. Также в каждом третьем дизайне приходится делать поле адреса из одной общей строки.

### Связанные проблема(ы)/PR(ы)

#524

2021-04-11 19:53 UTC, alroniks requested changes

2021-04-11 19:53 UTC, alroniks commented on _build/resolvers/resolve.settings.php
> +                $setting->save();
```suggestion
                $fields = explode(',', $setting->get('value'));
                $fields = array_unique(array_merge($fields, ['entrance', 'floor', 'text_address']));
                $setting->set('value', implode(',', $fields));
                $setting->save();
```

2021-04-11 19:53 UTC, alroniks commented on assets/components/minishop2/js/mgr/orders/orders.window.js
> +        console.log( miniShop2.config['order_address_fields']);
Need to remove debug code.

2021-04-11 19:53 UTC, alroniks commented on core/components/minishop2/lexicon/ru/manager.inc.php
>  $_lang['ms2_room'] = 'Комната';
Забыл поменять на Кв/Оф в админке

2021-04-11 19:53 UTC, alroniks commented on core/components/minishop2/lexicon/ru/default.inc.php
> +$_lang['ms2_frontend_room'] = 'Кв/Оф';
Как-то сокращение такое не очень. Может лучше просто оставить квартира? Домашний адрес чаще указывают

2021-04-12 06:51 UTC, alroniks commented on core/components/minishop2/lexicon/ru/default.inc.php
> +$_lang['ms2_frontend_room'] = 'Кв';
Тогда уж  точкой на конце, чтобы было понятно, что это сокращение.

2021-04-12 15:32 UTC, Ibochkarev requested changes

2021-04-12 15:32 UTC, Ibochkarev commented on assets/components/minishop2/js/mgr/orders/orders.window.js
> +        };
```suggestion
        };
```

2021-09-10 11:20 UTC, webinmd approved these changes

2021-09-12 10:01 UTC, merged