Добавил удобный выбор ресурса у производителя
modx-pro/miniShop2 pull request #650
Opened 2021-11-18 17:47 UTC by Electrica

### Что оно делает?
В настройках теперь можно указать родителей через запятую, который будут использованы для ограничения выборки ресурса в создании производителя

### Зачем это нужно?

Если много ресурсов, то не очень удобно. Часто бывает в разных контейнерах одинаковые наименования

### Связанные проблема(ы)/PR(ы)
#605

2021-11-18 17:51 UTC, Ibochkarev requested changes

2021-11-18 17:51 UTC, Ibochkarev commented on core/components/minishop2/processors/mgr/resources/getlist.class.php
> +        if($vendors = $this->modx->getOption('ms2_vendor_parents')){
```suggestion
        if ($vendors = $this->modx->getOption('ms2_vendor_parents')) {
```

2021-11-18 17:57 UTC, Ibochkarev requested changes

2021-11-18 17:57 UTC, Ibochkarev commented on core/components/minishop2/processors/mgr/resources/getlist.class.php
> +class msResourcesGetListProcessor extends modObjectGetListProcessor {
```suggestion
class msResourcesGetListProcessor extends modObjectGetListProcessor
{
```

2021-12-23 11:10 UTC, GulomovCreative commented
Мне кажется, что неправильно застолбить процессор [resources/getlist.class.php](core/components/minishop2/processors/mgr/resources/getlist.class.php) выборкой по ms2_vendor_parents. Появляется путаница, есть комбо miniShop2.combo.Resource и он запрашивает процессор resources/getlist.class.php и по дефолту возвращается выборкой ms2_vendor_parents.

Есть еще одна опасная штука, хоть и этот комбо в коде ms2 используется в одном месте, но в компонентах я уверен он повсеместно.

Тебе предложить решение? Или тут понятно? А то лень писать

2021-12-23 11:13 UTC, GulomovCreative requested changes
В settings/vendor/window.js где используется этот комбо, нужно в параметрах запроса кидать параметр, а в процессоре проверять и только тогда ограничивать выборку, а то некоторые компоненты сломаются

2022-01-12 09:26 UTC, Electrica commented
> В settings/vendor/window.js где используется этот комбо, нужно в параметрах запроса кидать параметр, а в процессоре проверять и только тогда ограничивать выборку, а то некоторые компоненты сломаются

Проверь плиз, так норм?

2023-02-03 07:51 UTC, closed without merging