Добавляем Роль при рег-ии пользователя
modx-pro/miniShop2 pull request #652
Opened 2021-11-25 15:40 UTC by Alexij2

Добавление поддержки роли для регистрации пользователя.

### Что оно делает?

Добавляет поддержку роли для регистрации пользователя. указывается Группа и после двоеточия РОЛЬ.

### Зачем это нужно?

Чтобы сразу регистрировать пользователя с нужной ролью.
**User:3** где 3 -это ID роли, так же роль можно писать текстом - MODX поддерживает это на уровне ядра.

2021-12-23 10:46 UTC, GulomovCreative requested changes
Немного сократил код, проверьте на разных версиях

2021-12-23 10:46 UTC, GulomovCreative commented on core/components/minishop2/model/minishop2/minishop2.class.php
>                          foreach ($groups as $group) {
```suggestion
                        $grouproles = array_map('trim', explode(',', $groups));
                        foreach ($grouproles as $grouprole) {
```

2021-12-23 10:46 UTC, GulomovCreative commented on core/components/minishop2/model/minishop2/minishop2.class.php
> +                            $customer->joinGroup($grouprole[0], $role);
```suggestion
                            list($group, $role) = array_pad(explode(':', $grouprole, 2), 2, null);
                            $role = is_numeric($role) ? (int) $role : $role;
                            $customer->joinGroup($group, $role);
```

2022-01-29 08:42 UTC, Ibochkarev commented
@Alexij2 внесете изменения или я сам?

2022-01-29 08:44 UTC, Alexij2 commented
Ох... сори не привык к тому что нужно как то следить за судьбой.
да, можно вносить без моего ведома. тк я не всегда успеваю следить за коррекциями.
Благодарю.

2022-05-20 10:13 UTC, biz87 approved these changes

2022-05-20 10:18 UTC, closed without merging