Работа ms2 с PHP8 #637
modx-pro/miniShop2 pull request #656
Opened 2021-12-09 23:33 UTC by CrazyBoy49z

### Что оно делает?

Работа ms2 с PHP8 #637

2021-12-24 06:11 UTC, alroniks requested changes
А можно описать смысл происходящего? Зачем? Почему?

2021-12-27 23:23 UTC, CrazyBoy49z commented
> А можно описать смысл происходящего? Зачем? Почему?

https://github.com/modx-pro/miniShop2/issues/637#issuecomment-990395046

2022-02-04 13:30 UTC, alroniks commented
С точки зрения архитектуры правильнее все же сделать новый метод, старый задепрекейтить и в старом вызывать новый. Это чтобы не плодить лишние условия.

Но если говорить про текущую реализацию, есть же вариант с проверкой на null прямо в условии.

```php
$usageOfAction = $action ?? 'status';
```

2022-02-06 11:12 UTC, CrazyBoy49z commented
> С точки зрения архитектуры правильнее все же сделать новый метод, старый задепрекейтить и в старом вызывать новый. Это чтобы не плодить лишние условия.
> 
> Но если говорить про текущую реализацию, есть же вариант с проверкой на null прямо в условии.
> 
> ```
> $usageOfAction = $action ?? 'status';
> ```

Проблема в том, что разраби в MODX встречал что использовали не null, а именно пустую строку(не понимаю за чем). А если переписывать на патерни, я только за. Так как это было б удобнее. Ну скинул пример, который решит эту проблему без критических изменений.

2022-02-06 11:14 UTC, CrazyBoy49z commented
Если б совсем было под моим контролем, я б уже либу развивал под php 8. Но здесь пока с етим сложно.

2022-05-20 09:46 UTC, biz87 commented
Будет учтено при разработке отдельной версии для MODX3

2022-05-20 09:46 UTC, closed without merging