Добавил очередь для писем
modx-pro/miniShop2 pull request #663
Opened 2022-01-12 20:00 UTC by Electrica

### Что оно делает?

Добавляет возможность отправлять письма в очередь для отправки пользователю

### Зачем это нужно?

Иногда письмо отправляется очень долго, и отправка заказа обрабатывается для пользователя долго.

Выведены настройки для включения работы очереди
Нужно добавить в крон скрипт /assets/components/minishop2/queue/mail.php

2022-01-29 09:34 UTC, Ibochkarev requested changes

2022-01-29 09:34 UTC, Ibochkarev commented on assets/components/minishop2/queue/mail.php
> +<?php
```suggestion
<?php

```

2022-01-29 09:34 UTC, Ibochkarev commented on assets/components/minishop2/queue/mail.php
> +$q->limit($modx->getOption('ms2_queue_limit', '' ,10));
```suggestion
$q->limit($modx->getOption('ms2_queue_limit', '', 10));
```

2022-01-29 09:34 UTC, Ibochkarev commented on assets/components/minishop2/queue/mail.php
> +}
```suggestion
} 
```

2022-12-18 07:08 UTC, biz87 commented
Закрываем в пользу компонента Scheduler

2022-12-18 07:08 UTC, closed without merging