Новый раздел с утилитами. Обновление превью изображений
modx-pro/miniShop2 pull request #868
Opened 2023-05-04 22:32 UTC by webinmd

### Что оно делает?

Добавлен новый раздел в пункты меню минишопа - Утилиты 
Первая утилита: Обновление превью изображений всех товаров

### Зачем это нужно?

Позволяет удобно перегенерировать превью изображений  в случае изменения параметров.
![image](https://user-images.githubusercontent.com/966234/236343510-018b4890-33f7-45be-8373-d492783ebd1a.png)

2023-05-05 07:01 UTC, Ruslan-Aleev commented
Прикольно придумано, это можно полезные и используемые скрипты, но простые для отдельного компонента, интегрировать в miniShop2

2023-05-05 08:05 UTC, webinmd commented
> Прикольно придумано, это можно полезные и используемые скрипты, но простые для отдельного компонента, интегрировать в miniShop2

Да, задумка именно такая. Так что если есть еще идеи по часто используемым скриптам, создавай issue

2023-05-05 11:35 UTC, biz87 requested changes
При нажатии на кнопку "Обновить", запускающую процесс - нужно настроить сброс оффсет на ноль

2023-05-05 21:31 UTC, Ruslan-Aleev commented
Имеет смысл добавить импорт из csv еще (https://github.com/modx-pro/miniShop2/blob/master/core/components/minishop2/import/csv.php), наверное отдельным PR, я про - https://ygoo.ru/modx-import-from-csv

2023-05-05 21:57 UTC, webinmd commented
> Имеет смысл добавить импорт из csv еще (https://github.com/modx-pro/miniShop2/blob/master/core/components/minishop2/import/csv.php), наверное отдельным PR, я про - https://ygoo.ru/modx-import-from-csv

#676

2023-05-06 04:17 UTC, biz87 approved these changes

2023-05-08 06:04 UTC, merged