Вывел email менеджеров в разделе Заказы
modx-pro/miniShop2 pull request #897
Opened 2023-08-03 14:45 UTC by Ruslan-Aleev

### Что оно делает?
Вывел email менеджеров в разделе Заказы, т.к. иногда не очевидно куда все уходит (часто клиенты спрашивали, или просили менять ящики).
Теперь список email перед глазами, будет понятнее.

![emails_1](https://github.com/modx-pro/miniShop2/assets/12523676/eea31c25-18de-4a0c-b4f6-b857386df8f7)

![emails_2](https://github.com/modx-pro/miniShop2/assets/12523676/74657c1a-eb5b-4c27-8900-7265ba1d1054)

### Связанные проблема(ы)/PR(ы)
Нет

2023-08-03 16:12 UTC, GulomovCreative requested changes

2023-08-03 16:12 UTC, GulomovCreative commented on assets/components/minishop2/js/mgr/orders/orders.form.js
> +        let emailManagerInfo = '<small>' + _('ms2_orders_form_email_manager') + ' ' + (emailManager ? emailManager : _('ms2_orders_form_email_manager_empty')) + '</small>';
```suggestion
        const emailManagerInfo = '<small>' + _('ms2_orders_form_email_manager') + ' ' + emailManager || _('ms2_orders_form_email_manager_empty') + '</small>';
```

Здесь можно обойтись оператором ИЛИ

2023-08-03 16:12 UTC, GulomovCreative commented on assets/components/minishop2/js/mgr/orders/orders.form.js
> +        let emailManagerInfo = '<small>' + _('ms2_orders_form_email_manager') + ' ' + (emailManager ? emailManager : _('ms2_orders_form_email_manager_empty')) + '</small>';
```suggestion
        const emailManagerInfo = '<small>' + _('ms2_orders_form_email_manager') + ' ' + MODx.config.ms2_email_manager || _('ms2_orders_form_email_manager_empty')) + '</small>';
```

Лучше вообще вот так

2023-09-03 06:43 UTC, GulomovCreative reviewed
По коду вопросов нет

2024-07-16 19:04 UTC, webinmd commented
господа, без обид, но выглядит как-то будто не место этой информации в том месте

2024-07-16 19:37 UTC, Ruslan-Aleev commented
Не знай, по мне так самое место, инфа для менеджеров полезная. Но если что - можешь закрыть PR

2024-08-04 08:38 UTC, biz87 commented
Я согласен с @webinmd - эта информация тут не нужна. 
по мере запроса ее проще добавить в нужный проект

2024-08-04 08:38 UTC, closed without merging